site_name: 'Утильсбор за машины, произведенные в Кахазстане'
docs_dir: docs
repo_url: https://github.com/zachestniyutil/avto_iz_KZ
theme:
  name: material
  custom_dir: overrides
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/
plugins:
  - search:
      indexing: 'full'
      lang:
        - en
        - ru
      min_search_length: 3
      prebuild_index: false
      separator: "[\\s\\-]+"

nav:
- Главное: 
  - "Описание проблемы": index.md
  - "Глоссарий": glossary.md
  - "Кому придется платить": faq.md
  - "Сколько требуют доплатить?": howmuch.md
  - "Последствия": consequences.md
  - "Что делать?": todo.md
  - "Позиция таможни": customs.md
  - "Контакты" : contacts.md
  
- Ситуации: 
  - "Дроп": drop.md
  - "Аннулирование ЭПТС": disabled.md
  
- Документы:
  - "CT-KZ": ctkz.md
  - "ДТ": dt.md
  - "Постановление №1291": 1291.md
  - "ТПО": tpo.md
  - "ЭПТС": epts.md
  - "ИМ40": im40.md
  
- Судебная практика:
  - "Вынесенные решения" : protocols.md